SELECT
    PERSON.ID AS ID, 
    PERSON.UserName AS UserName,
    PERSON_PARENT.UserName AS ParentUserName
FROM USER AS PERSON
LEFT JOIN USER AS PERSON_PARENT ON PERSON.Parent = PERSON_PARENT.ID
ORDER BY PERSON.ID ASC;